# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 902)
        MainWindow.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, -25, 1251, 951))
        self.tabWidget.setStyleSheet("font: 14px;")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.MainToolBar = QtWidgets.QFrame(self.tab)
        self.MainToolBar.setGeometry(QtCore.QRect(0, 0, 1261, 35))
        self.MainToolBar.setStyleSheet("QPushButton{\n"
"    border: 0px;    \n"
"    font: 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font: bold;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(227, 253, 252);\n"
"    font: bold;\n"
"}\n"
"QFrame{\n"
"    border-bottom: 2px solid rgba(227, 227, 227, 255);\n"
"}\n"
"")
        self.MainToolBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainToolBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainToolBar.setObjectName("MainToolBar")
        self.pushButton = QtWidgets.QPushButton(self.MainToolBar)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 61, 31))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.MainToolBar)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 0, 80, 31))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.MainToolBar)
        self.pushButton_7.setGeometry(QtCore.QRect(152, 0, 231, 31))
        self.pushButton_7.setStyleSheet("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_26 = QtWidgets.QPushButton(self.MainToolBar)
        self.pushButton_26.setGeometry(QtCore.QRect(390, 0, 221, 31))
        self.pushButton_26.setStyleSheet("")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_39 = QtWidgets.QPushButton(self.MainToolBar)
        self.pushButton_39.setGeometry(QtCore.QRect(613, 0, 51, 31))
        self.pushButton_39.setStyleSheet("")
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_45 = QtWidgets.QPushButton(self.MainToolBar)
        self.pushButton_45.setGeometry(QtCore.QRect(670, 0, 101, 30))
        self.pushButton_45.setStyleSheet("")
        self.pushButton_45.setObjectName("pushButton_45")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(0, 30, 61, 3))
        self.line.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Browser = QtWebEngineWidgets.QWebEngineView(self.tab)
        self.Browser.setGeometry(QtCore.QRect(0, 70, 1241, 831))
        self.Browser.setObjectName("Browser")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(0, 40, 1151, 31))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QLineEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_40 = QtWidgets.QPushButton(self.tab)
        self.pushButton_40.setGeometry(QtCore.QRect(1160, 40, 81, 31))
        self.pushButton_40.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 8px;\n"
"}\n"
"")
        self.pushButton_40.setObjectName("pushButton_40")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.MainToolBar_2 = QtWidgets.QFrame(self.tab_2)
        self.MainToolBar_2.setGeometry(QtCore.QRect(0, 0, 1261, 35))
        self.MainToolBar_2.setStyleSheet("QPushButton{\n"
"    border: 0px;    \n"
"    font: 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font: bold;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(227, 253, 252);\n"
"    font: bold;\n"
"}\n"
"QFrame{\n"
"    border-bottom: 2px solid rgba(227, 227, 227, 255);\n"
"}\n"
"")
        self.MainToolBar_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainToolBar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainToolBar_2.setObjectName("MainToolBar_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.MainToolBar_2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 61, 31))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.MainToolBar_2)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 0, 80, 31))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.MainToolBar_2)
        self.pushButton_8.setGeometry(QtCore.QRect(152, 0, 231, 31))
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_25 = QtWidgets.QPushButton(self.MainToolBar_2)
        self.pushButton_25.setGeometry(QtCore.QRect(390, 0, 221, 31))
        self.pushButton_25.setStyleSheet("")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_38 = QtWidgets.QPushButton(self.MainToolBar_2)
        self.pushButton_38.setGeometry(QtCore.QRect(613, 0, 51, 31))
        self.pushButton_38.setStyleSheet("")
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_61 = QtWidgets.QPushButton(self.MainToolBar_2)
        self.pushButton_61.setGeometry(QtCore.QRect(670, 0, 101, 30))
        self.pushButton_61.setStyleSheet("")
        self.pushButton_61.setObjectName("pushButton_61")
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(70, 30, 80, 3))
        self.line_3.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.label.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox.setGeometry(QtCore.QRect(130, 40, 71, 22))
        self.spinBox.setStyleSheet("QSpinBox {\n"
"    background-color: white;\n"
"    border: 1px solid #a6a6a6;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    color: #555555;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid #7e93f3;\n"
"}\n"
"")
        self.spinBox.setMaximum(1000)
        self.spinBox.setProperty("value", 6)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_2.setGeometry(QtCore.QRect(210, 40, 71, 22))
        self.spinBox_2.setStyleSheet("QSpinBox {\n"
"    background-color: white;\n"
"    border: 1px solid #a6a6a6;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    color: #555555;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid #7e93f3;\n"
"}\n"
"")
        self.spinBox_2.setMaximum(1000)
        self.spinBox_2.setProperty("value", 6)
        self.spinBox_2.setObjectName("spinBox_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 830, 491, 71))
        self.plainTextEdit.setStyleSheet("\n"
"background-color: white;\n"
"color: #003399;\n"
"")
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(490, 830, 541, 71))
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(1020, 40, 121, 23))
        self.pushButton_10.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 4px;\n"
"padding-top: 4px;\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_14.setGeometry(QtCore.QRect(1150, 40, 91, 23))
        self.pushButton_14.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 4px;\n"
"padding-top: 4px;\n"
"}\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 70, 1241, 761))
        self.tableWidget_3.setStyleSheet("QTableWidget\n"
"{\n"
"    background-color: white;\n"
"    gridline-color: lightgray;\n"
"    border: 1px solid lightgray;\n"
"    font:16px;\n"
"}\n"
"\n"
"QTableWidget::item\n"
"{\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #add8e6, stop: 1 #ffffff);\n"
"    border: 1px solid #87CEFA;\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.tableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(6)
        self.tableWidget_3.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 0, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(165)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(35)
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_27.setGeometry(QtCore.QRect(1040, 835, 201, 61))
        self.pushButton_27.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 4px;\n"
"padding-top: 4px;\n"
"}\n"
"")
        self.pushButton_27.setObjectName("pushButton_27")
        self.fontComboBox = QtWidgets.QFontComboBox(self.tab_2)
        self.fontComboBox.setGeometry(QtCore.QRect(430, 40, 201, 22))
        self.fontComboBox.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.fontComboBox.setObjectName("fontComboBox")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_3.setGeometry(QtCore.QRect(640, 40, 41, 22))
        self.spinBox_3.setStyleSheet("QSpinBox {\n"
"    background-color: white;\n"
"    border: 1px solid #a6a6a6;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    color: #555555;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid #7e93f3;\n"
"}\n"
"")
        self.spinBox_3.setMinimum(6)
        self.spinBox_3.setMaximum(50)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(350, 40, 71, 21))
        self.label_9.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(310, 40, 31, 23))
        self.pushButton_11.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 8px;\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.MainToolBar_3 = QtWidgets.QFrame(self.tab_3)
        self.MainToolBar_3.setGeometry(QtCore.QRect(0, 0, 1261, 35))
        self.MainToolBar_3.setStyleSheet("QPushButton{\n"
"    border: 0px;    \n"
"    font: 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font: bold;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(227, 253, 252);\n"
"    font: bold;\n"
"}\n"
"QFrame{\n"
"    border-bottom: 2px solid rgba(227, 227, 227, 255);\n"
"}\n"
"")
        self.MainToolBar_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainToolBar_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainToolBar_3.setObjectName("MainToolBar_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.MainToolBar_3)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 0, 61, 31))
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.MainToolBar_3)
        self.pushButton_6.setGeometry(QtCore.QRect(70, 0, 80, 31))
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.MainToolBar_3)
        self.pushButton_9.setGeometry(QtCore.QRect(152, 0, 231, 31))
        self.pushButton_9.setStyleSheet("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.line_2 = QtWidgets.QFrame(self.MainToolBar_3)
        self.line_2.setGeometry(QtCore.QRect(152, 30, 231, 3))
        self.line_2.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_24 = QtWidgets.QPushButton(self.MainToolBar_3)
        self.pushButton_24.setGeometry(QtCore.QRect(390, 0, 221, 31))
        self.pushButton_24.setStyleSheet("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_37 = QtWidgets.QPushButton(self.MainToolBar_3)
        self.pushButton_37.setGeometry(QtCore.QRect(613, 0, 51, 31))
        self.pushButton_37.setStyleSheet("")
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_47 = QtWidgets.QPushButton(self.MainToolBar_3)
        self.pushButton_47.setGeometry(QtCore.QRect(670, 0, 101, 30))
        self.pushButton_47.setStyleSheet("")
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_15.setGeometry(QtCore.QRect(1150, 40, 91, 23))
        self.pushButton_15.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 4px;\n"
"padding-top: 4px;\n"
"}\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_16.setGeometry(QtCore.QRect(1020, 40, 121, 23))
        self.pushButton_16.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 4px;\n"
"padding-top: 4px;\n"
"}\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 121, 21))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 70, 1241, 791))
        self.tableWidget_2.setStyleSheet("QTableWidget\n"
"{\n"
"    background-color: white;\n"
"    gridline-color: lightgray;\n"
"    border: 1px solid lightgray;\n"
"    font:16px;\n"
"}\n"
"\n"
"QTableWidget::item\n"
"{\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #add8e6, stop: 1 #ffffff);\n"
"    border: 1px solid #87CEFA;\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(165)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(35)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(140, 40, 141, 22))
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(10, 870, 1221, 31))
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(350, 40, 71, 21))
        self.label_10.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.fontComboBox_2 = QtWidgets.QFontComboBox(self.tab_3)
        self.fontComboBox_2.setGeometry(QtCore.QRect(430, 40, 201, 22))
        self.fontComboBox_2.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.fontComboBox_2.setObjectName("fontComboBox_2")
        self.spinBox_4 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_4.setGeometry(QtCore.QRect(640, 40, 41, 22))
        self.spinBox_4.setStyleSheet("QSpinBox {\n"
"    background-color: white;\n"
"    border: 1px solid #a6a6a6;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    color: #555555;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid #7e93f3;\n"
"}\n"
"")
        self.spinBox_4.setMinimum(6)
        self.spinBox_4.setMaximum(50)
        self.spinBox_4.setObjectName("spinBox_4")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_12.setGeometry(QtCore.QRect(310, 40, 31, 23))
        self.pushButton_12.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 8px;\n"
"}\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.MainToolBar_4 = QtWidgets.QFrame(self.tab_4)
        self.MainToolBar_4.setGeometry(QtCore.QRect(0, 0, 1261, 35))
        self.MainToolBar_4.setStyleSheet("QPushButton{\n"
"    border: 0px;    \n"
"    font: 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font: bold;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(227, 253, 252);\n"
"    font: bold;\n"
"}\n"
"QFrame{\n"
"    border-bottom: 2px solid rgba(227, 227, 227, 255);\n"
"}\n"
"")
        self.MainToolBar_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainToolBar_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainToolBar_4.setObjectName("MainToolBar_4")
        self.pushButton_20 = QtWidgets.QPushButton(self.MainToolBar_4)
        self.pushButton_20.setGeometry(QtCore.QRect(0, 0, 61, 31))
        self.pushButton_20.setStyleSheet("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.MainToolBar_4)
        self.pushButton_21.setGeometry(QtCore.QRect(70, 0, 80, 31))
        self.pushButton_21.setStyleSheet("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.MainToolBar_4)
        self.pushButton_22.setGeometry(QtCore.QRect(152, 0, 231, 31))
        self.pushButton_22.setStyleSheet("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.MainToolBar_4)
        self.pushButton_23.setGeometry(QtCore.QRect(390, 0, 221, 31))
        self.pushButton_23.setStyleSheet("")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_36 = QtWidgets.QPushButton(self.MainToolBar_4)
        self.pushButton_36.setGeometry(QtCore.QRect(613, 0, 51, 31))
        self.pushButton_36.setStyleSheet("")
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_51 = QtWidgets.QPushButton(self.MainToolBar_4)
        self.pushButton_51.setGeometry(QtCore.QRect(670, 0, 101, 30))
        self.pushButton_51.setStyleSheet("")
        self.pushButton_51.setObjectName("pushButton_51")
        self.line_4 = QtWidgets.QFrame(self.tab_4)
        self.line_4.setGeometry(QtCore.QRect(390, 30, 221, 3))
        self.line_4.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_29.setGeometry(QtCore.QRect(1040, 40, 101, 23))
        self.pushButton_29.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 4px;\n"
"padding-top: 4px;\n"
"}\n"
"")
        self.pushButton_29.setObjectName("pushButton_29")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(140, 40, 121, 22))
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.pushButton_30 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_30.setGeometry(QtCore.QRect(1150, 40, 91, 23))
        self.pushButton_30.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 4px;\n"
"padding-top: 4px;\n"
"}\n"
"")
        self.pushButton_30.setObjectName("pushButton_30")
        self.comboBox = QtWidgets.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(700, 40, 331, 22))
        self.comboBox.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 70, 1241, 791))
        self.tableWidget_4.setStyleSheet("QTableWidget\n"
"{\n"
"    background-color: white;\n"
"    gridline-color: lightgray;\n"
"    border: 1px solid lightgray;\n"
"    font:16px;\n"
"}\n"
"\n"
"QTableWidget::item\n"
"{\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #add8e6, stop: 1 #ffffff);\n"
"    border: 1px solid #87CEFA;\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(6)
        self.tableWidget_4.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 0, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(165)
        self.tableWidget_4.verticalHeader().setDefaultSectionSize(35)
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(10, 870, 1221, 31))
        self.label_8.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(350, 40, 81, 21))
        self.label_11.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.fontComboBox_3 = QtWidgets.QFontComboBox(self.tab_4)
        self.fontComboBox_3.setGeometry(QtCore.QRect(430, 40, 201, 22))
        self.fontComboBox_3.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.fontComboBox_3.setObjectName("fontComboBox_3")
        self.spinBox_5 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_5.setGeometry(QtCore.QRect(640, 40, 41, 22))
        self.spinBox_5.setStyleSheet("QSpinBox {\n"
"    background-color: white;\n"
"    border: 1px solid #a6a6a6;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    color: #555555;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid #7e93f3;\n"
"}\n"
"")
        self.spinBox_5.setMinimum(6)
        self.spinBox_5.setMaximum(50)
        self.spinBox_5.setObjectName("spinBox_5")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_13.setGeometry(QtCore.QRect(310, 40, 31, 23))
        self.pushButton_13.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 8px;\n"
"}\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.MainToolBar_5 = QtWidgets.QFrame(self.tab_5)
        self.MainToolBar_5.setGeometry(QtCore.QRect(0, 0, 1261, 35))
        self.MainToolBar_5.setStyleSheet("QPushButton{\n"
"    border: 0px;    \n"
"    font: 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font: bold;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(227, 253, 252);\n"
"    font: bold;\n"
"}\n"
"QFrame{\n"
"    border-bottom: 2px solid rgba(227, 227, 227, 255);\n"
"}\n"
"")
        self.MainToolBar_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainToolBar_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainToolBar_5.setObjectName("MainToolBar_5")
        self.pushButton_31 = QtWidgets.QPushButton(self.MainToolBar_5)
        self.pushButton_31.setGeometry(QtCore.QRect(0, 0, 61, 31))
        self.pushButton_31.setStyleSheet("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.MainToolBar_5)
        self.pushButton_32.setGeometry(QtCore.QRect(70, 0, 80, 31))
        self.pushButton_32.setStyleSheet("")
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.MainToolBar_5)
        self.pushButton_33.setGeometry(QtCore.QRect(152, 0, 231, 31))
        self.pushButton_33.setStyleSheet("")
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.MainToolBar_5)
        self.pushButton_34.setGeometry(QtCore.QRect(390, 0, 221, 31))
        self.pushButton_34.setStyleSheet("")
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.MainToolBar_5)
        self.pushButton_35.setGeometry(QtCore.QRect(613, 0, 51, 31))
        self.pushButton_35.setStyleSheet("")
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_50 = QtWidgets.QPushButton(self.MainToolBar_5)
        self.pushButton_50.setGeometry(QtCore.QRect(670, 0, 101, 30))
        self.pushButton_50.setStyleSheet("")
        self.pushButton_50.setObjectName("pushButton_50")
        self.line_5 = QtWidgets.QFrame(self.tab_5)
        self.line_5.setGeometry(QtCore.QRect(613, 30, 51, 3))
        self.line_5.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton_43 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_43.setGeometry(QtCore.QRect(1100, 40, 141, 23))
        self.pushButton_43.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 6px;\n"
"}\n"
"")
        self.pushButton_43.setObjectName("pushButton_43")
        self.widget = QtWidgets.QWidget(self.tab_5)
        self.widget.setGeometry(QtCore.QRect(10, 70, 821, 831))
        self.widget.setObjectName("widget")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 40, 821, 22))
        self.comboBox_2.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(840, 40, 131, 21))
        self.label_6.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.pushButton_44 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_44.setGeometry(QtCore.QRect(980, 40, 111, 23))
        self.pushButton_44.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 6px;\n"
"}\n"
"")
        self.pushButton_44.setObjectName("pushButton_44")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget.setGeometry(QtCore.QRect(840, 70, 401, 831))
        self.tableWidget.setStyleSheet("QTableWidget\n"
"{\n"
"    background-color: white;\n"
"    gridline-color: lightgray;\n"
"    border: 1px solid lightgray;\n"
"    font:16px;\n"
"}\n"
"\n"
"QTableWidget::item\n"
"{\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #add8e6, stop: 1 #ffffff);\n"
"    border: 1px solid #87CEFA;\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(199)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(150)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.tab_5, "")
        self.NeuralNetworkTab = QtWidgets.QWidget()
        self.NeuralNetworkTab.setObjectName("NeuralNetworkTab")
        self.MainToolBar_6 = QtWidgets.QFrame(self.NeuralNetworkTab)
        self.MainToolBar_6.setGeometry(QtCore.QRect(0, 0, 1261, 35))
        self.MainToolBar_6.setStyleSheet("QPushButton{\n"
"    border: 0px;    \n"
"    font: 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font: bold;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(227, 253, 252);\n"
"    font: bold;\n"
"}\n"
"QFrame{\n"
"    border-bottom: 2px solid rgba(227, 227, 227, 255);\n"
"}\n"
"")
        self.MainToolBar_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainToolBar_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainToolBar_6.setObjectName("MainToolBar_6")
        self.pushButton_17 = QtWidgets.QPushButton(self.MainToolBar_6)
        self.pushButton_17.setGeometry(QtCore.QRect(0, 0, 61, 31))
        self.pushButton_17.setStyleSheet("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.MainToolBar_6)
        self.pushButton_18.setGeometry(QtCore.QRect(70, 0, 80, 31))
        self.pushButton_18.setStyleSheet("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.MainToolBar_6)
        self.pushButton_19.setGeometry(QtCore.QRect(152, 0, 231, 31))
        self.pushButton_19.setStyleSheet("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.line_6 = QtWidgets.QFrame(self.MainToolBar_6)
        self.line_6.setGeometry(QtCore.QRect(670, 30, 101, 3))
        self.line_6.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.pushButton_28 = QtWidgets.QPushButton(self.MainToolBar_6)
        self.pushButton_28.setGeometry(QtCore.QRect(390, 0, 221, 31))
        self.pushButton_28.setStyleSheet("")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_41 = QtWidgets.QPushButton(self.MainToolBar_6)
        self.pushButton_41.setGeometry(QtCore.QRect(613, 0, 51, 31))
        self.pushButton_41.setStyleSheet("")
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.MainToolBar_6)
        self.pushButton_42.setGeometry(QtCore.QRect(670, 0, 101, 30))
        self.pushButton_42.setStyleSheet("")
        self.pushButton_42.setObjectName("pushButton_42")
        self.stackedWidget = QtWidgets.QStackedWidget(self.NeuralNetworkTab)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 40, 1241, 861))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.label_12 = QtWidgets.QLabel(self.Settings)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 1151, 31))
        self.label_12.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"    padding: 5px;\n"
"    font: 14pt \"Segoe UI\";\n"
"}")
        self.label_12.setObjectName("label_12")
        self.groupBox = QtWidgets.QGroupBox(self.Settings)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 431, 431))
        self.groupBox.setObjectName("groupBox")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(20, 30, 231, 31))
        self.label_14.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 30, 161, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QLineEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(20, 70, 231, 31))
        self.label_15.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(260, 70, 161, 31))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QLineEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_46 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_46.setGeometry(QtCore.QRect(20, 380, 401, 31))
        self.pushButton_46.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 6px;\n"
"}\n"
"")
        self.pushButton_46.setObjectName("pushButton_46")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(20, 110, 191, 31))
        self.label_20.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_20.setObjectName("label_20")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(260, 110, 161, 31))
        self.comboBox_5.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(260, 190, 161, 31))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QLineEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(20, 190, 191, 31))
        self.label_17.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(20, 230, 191, 31))
        self.label_19.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_19.setObjectName("label_19")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(260, 230, 161, 31))
        self.comboBox_4.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(20, 150, 191, 31))
        self.label_18.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_18.setObjectName("label_18")
        self.comboBox_10 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_10.setGeometry(QtCore.QRect(260, 150, 161, 31))
        self.comboBox_10.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.label_43 = QtWidgets.QLabel(self.groupBox)
        self.label_43.setGeometry(QtCore.QRect(20, 340, 231, 31))
        self.label_43.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.groupBox)
        self.label_44.setGeometry(QtCore.QRect(260, 340, 161, 31))
        self.label_44.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #aa0000;\n"
"    font-size: 20px;\n"
"}")
        self.label_44.setObjectName("label_44")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Settings)
        self.groupBox_3.setGeometry(QtCore.QRect(460, 40, 361, 191))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(10, 70, 171, 31))
        self.label_21.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_21.setObjectName("label_21")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_6.setGeometry(QtCore.QRect(190, 70, 161, 31))
        self.comboBox_6.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox_6.setEditable(False)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(10, 30, 171, 31))
        self.label_22.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(190, 30, 161, 31))
        self.label_23.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(10, 110, 171, 31))
        self.label_24.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_24.setObjectName("label_24")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_7.setGeometry(QtCore.QRect(190, 110, 161, 31))
        self.comboBox_7.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.groupBox_4 = QtWidgets.QGroupBox(self.Settings)
        self.groupBox_4.setGeometry(QtCore.QRect(460, 240, 361, 231))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.label_26.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(190, 30, 161, 31))
        self.label_27.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(10, 70, 161, 31))
        self.label_28.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(190, 70, 161, 31))
        self.label_29.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(10, 110, 161, 31))
        self.label_30.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setGeometry(QtCore.QRect(190, 110, 161, 31))
        self.label_31.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setGeometry(QtCore.QRect(10, 150, 161, 31))
        self.label_32.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(190, 150, 161, 31))
        self.label_33.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setGeometry(QtCore.QRect(10, 190, 161, 31))
        self.label_34.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_4)
        self.label_35.setGeometry(QtCore.QRect(190, 190, 161, 31))
        self.label_35.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_35.setObjectName("label_35")
        self.groupBox_6 = QtWidgets.QGroupBox(self.Settings)
        self.groupBox_6.setGeometry(QtCore.QRect(830, 40, 401, 211))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_48 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_48.setGeometry(QtCore.QRect(10, 160, 181, 31))
        self.pushButton_48.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 6px;\n"
"}\n"
"")
        self.pushButton_48.setObjectName("pushButton_48")
        self.label_36 = QtWidgets.QLabel(self.groupBox_6)
        self.label_36.setGeometry(QtCore.QRect(10, 30, 171, 31))
        self.label_36.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_36.setObjectName("label_36")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(10, 70, 381, 81))
        self.plainTextEdit_3.setStyleSheet("QPlainTextEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QPlainTextEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QPlainTextEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.pushButton_54 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_54.setGeometry(QtCore.QRect(210, 160, 181, 31))
        self.pushButton_54.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 6px;\n"
"}\n"
"")
        self.pushButton_54.setObjectName("pushButton_54")
        self.groupBox_7 = QtWidgets.QGroupBox(self.Settings)
        self.groupBox_7.setGeometry(QtCore.QRect(830, 260, 401, 211))
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_49 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_49.setGeometry(QtCore.QRect(10, 170, 381, 31))
        self.pushButton_49.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 6px;\n"
"}\n"
"")
        self.pushButton_49.setObjectName("pushButton_49")
        self.label_37 = QtWidgets.QLabel(self.groupBox_7)
        self.label_37.setGeometry(QtCore.QRect(10, 30, 171, 41))
        self.label_37.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_37.setObjectName("label_37")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.groupBox_7)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(10, 80, 381, 81))
        self.plainTextEdit_4.setStyleSheet("QPlainTextEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QPlainTextEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QPlainTextEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.plainTextEdit_4.setReadOnly(True)
        self.plainTextEdit_4.setPlainText("")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.pushButton_57 = QtWidgets.QPushButton(self.Settings)
        self.pushButton_57.setGeometry(QtCore.QRect(1160, 0, 31, 31))
        self.pushButton_57.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 6px;\n"
"}\n"
"")
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_58 = QtWidgets.QPushButton(self.Settings)
        self.pushButton_58.setGeometry(QtCore.QRect(1200, 0, 31, 31))
        self.pushButton_58.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 6px;\n"
"}\n"
"")
        self.pushButton_58.setObjectName("pushButton_58")
        self.stackedWidget.addWidget(self.Settings)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 1201, 31))
        self.label_13.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"    padding: 5px;\n"
"    font: 14pt \"Segoe UI\";\n"
"}")
        self.label_13.setObjectName("label_13")
        self.groupBox_12 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 30, 401, 821))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_38 = QtWidgets.QLabel(self.groupBox_12)
        self.label_38.setGeometry(QtCore.QRect(20, 30, 371, 41))
        self.label_38.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_38.setObjectName("label_38")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_6.setGeometry(QtCore.QRect(20, 70, 361, 31))
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QLineEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_39 = QtWidgets.QLabel(self.groupBox_12)
        self.label_39.setGeometry(QtCore.QRect(20, 110, 371, 41))
        self.label_39.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_39.setObjectName("label_39")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_7.setGeometry(QtCore.QRect(20, 150, 361, 31))
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"\n"
"QLineEdit:focused {\n"
"    border: 1px solid #0077C9;\n"
"}\n"
"")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_53 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_53.setGeometry(QtCore.QRect(10, 200, 381, 31))
        self.pushButton_53.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 6px;\n"
"}\n"
"")
        self.pushButton_53.setObjectName("pushButton_53")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_12)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 250, 381, 561))
        self.listWidget_2.setStyleSheet("QListWidget {\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: lightblue;\n"
"}\n"
"")
        self.listWidget_2.setObjectName("listWidget_2")
        self.groupBox_13 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_13.setGeometry(QtCore.QRect(420, 30, 821, 821))
        self.groupBox_13.setObjectName("groupBox_13")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.groupBox_13)
        self.tableWidget_5.setGeometry(QtCore.QRect(20, 80, 791, 131))
        self.tableWidget_5.setStyleSheet("QTableWidget\n"
"{\n"
"    background-color: white;\n"
"    gridline-color: lightgray;\n"
"    border: 1px solid lightgray;\n"
"    font:16px;\n"
"}\n"
"\n"
"QTableWidget::item\n"
"{\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #add8e6, stop: 1 #ffffff);\n"
"    border: 1px solid #87CEFA;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.tableWidget_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        self.tableWidget_5.horizontalHeader().setVisible(False)
        self.tableWidget_5.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget_5.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget_5.verticalHeader().setDefaultSectionSize(60)
        self.tableWidget_5.verticalHeader().setMinimumSectionSize(60)
        self.tableWidget_6 = QtWidgets.QTableWidget(self.groupBox_13)
        self.tableWidget_6.setGeometry(QtCore.QRect(20, 330, 791, 131))
        self.tableWidget_6.setStyleSheet("QTableWidget\n"
"{\n"
"    background-color: white;\n"
"    gridline-color: lightgray;\n"
"    border: 1px solid lightgray;\n"
"    font:16px;\n"
"}\n"
"\n"
"QTableWidget::item\n"
"{\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #add8e6, stop: 1 #ffffff);\n"
"    border: 1px solid #87CEFA;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.tableWidget_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(0)
        self.tableWidget_6.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(1, item)
        self.tableWidget_6.horizontalHeader().setVisible(False)
        self.tableWidget_6.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget_6.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget_6.verticalHeader().setDefaultSectionSize(60)
        self.tableWidget_6.verticalHeader().setMinimumSectionSize(60)
        self.label_41 = QtWidgets.QLabel(self.groupBox_13)
        self.label_41.setGeometry(QtCore.QRect(20, 30, 361, 41))
        self.label_41.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_13)
        self.label_42.setGeometry(QtCore.QRect(20, 280, 131, 41))
        self.label_42.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_42.setObjectName("label_42")
        self.pushButton_55 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_55.setGeometry(QtCore.QRect(20, 230, 791, 31))
        self.pushButton_55.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 6px;\n"
"}\n"
"")
        self.pushButton_55.setObjectName("pushButton_55")
        self.label_45 = QtWidgets.QLabel(self.groupBox_13)
        self.label_45.setGeometry(QtCore.QRect(20, 480, 781, 41))
        self.label_45.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: #003399;\n"
"}")
        self.label_45.setObjectName("label_45")
        self.HIDDENGRAPH = QtWidgets.QGroupBox(self.page_2)
        self.HIDDENGRAPH.setEnabled(False)
        self.HIDDENGRAPH.setGeometry(QtCore.QRect(420, 1000, 821, 361))
        self.HIDDENGRAPH.setObjectName("HIDDENGRAPH")
        self.widget_2 = QtWidgets.QWidget(self.HIDDENGRAPH)
        self.widget_2.setGeometry(QtCore.QRect(10, 30, 801, 281))
        self.widget_2.setObjectName("widget_2")
        self.pushButton_56 = QtWidgets.QPushButton(self.HIDDENGRAPH)
        self.pushButton_56.setGeometry(QtCore.QRect(10, 320, 631, 31))
        self.pushButton_56.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 6px;\n"
"}\n"
"")
        self.pushButton_56.setObjectName("pushButton_56")
        self.comboBox_9 = QtWidgets.QComboBox(self.HIDDENGRAPH)
        self.comboBox_9.setGeometry(QtCore.QRect(650, 320, 161, 31))
        self.comboBox_9.setStyleSheet("QComboBox\n"
"{\n"
"    background-color: white;\n"
"    border: 1px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(200, 200, 200, 0.2);\n"
"}\n"
"\n"
"QComboBox:!enabled\n"
"{\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.pushButton_59 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_59.setGeometry(QtCore.QRect(1200, 0, 31, 31))
        self.pushButton_59.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 6px;\n"
"}\n"
"")
        self.pushButton_59.setObjectName("pushButton_59")
        self.pushButton_60 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_60.setGeometry(QtCore.QRect(1160, 0, 31, 31))
        self.pushButton_60.setStyleSheet("QPushButton\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #6da8f7, stop: 1 #4b7dda);\n"
"color: white;\n"
"border-radius: 5px;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #4b7dda, stop: 1 #6da8f7);\n"
"padding-left: 8px;\n"
"padding-top: 6px;\n"
"}\n"
"")
        self.pushButton_60.setObjectName("pushButton_60")
        self.stackedWidget.addWidget(self.page_2)
        self.tabWidget.addTab(self.NeuralNetworkTab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "МАИ анализатор"))
        self.pushButton.setText(_translate("MainWindow", "Поиск"))
        self.pushButton_4.setText(_translate("MainWindow", "Таблица"))
        self.pushButton_7.setText(_translate("MainWindow", "Матрица парных сравнений"))
        self.pushButton_26.setText(_translate("MainWindow", "Сравнения у альтернатив"))
        self.pushButton_39.setText(_translate("MainWindow", "Итог"))
        self.pushButton_45.setText(_translate("MainWindow", "Нейросети"))
        self.lineEdit.setText(_translate("MainWindow", "https://www.google.com"))
        self.pushButton_40.setText(_translate("MainWindow", "Url"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Поисковик"))
        self.pushButton_2.setText(_translate("MainWindow", "Поиск"))
        self.pushButton_3.setText(_translate("MainWindow", "Таблица"))
        self.pushButton_8.setText(_translate("MainWindow", "Матрица парных сравнений"))
        self.pushButton_25.setText(_translate("MainWindow", "Сравнения у альтернатив"))
        self.pushButton_38.setText(_translate("MainWindow", "Итог"))
        self.pushButton_61.setText(_translate("MainWindow", "Нейросети"))
        self.label.setText(_translate("MainWindow", "Размер таблицы:"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Параметры могут распологаться только вниз, вдоль левого края\n"
"Альтернативы могут распологаться только вправо, вдоль верхнего края"))
        self.pushButton_10.setText(_translate("MainWindow", "Сохранить"))
        self.pushButton_14.setText(_translate("MainWindow", "Очистить"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 1)
        item.setText(_translate("MainWindow", "Альтернатива 1"))
        item = self.tableWidget_3.item(0, 2)
        item.setText(_translate("MainWindow", "Альтернатива 2"))
        item = self.tableWidget_3.item(0, 3)
        item.setText(_translate("MainWindow", "Альтернатива 3"))
        item = self.tableWidget_3.item(1, 0)
        item.setText(_translate("MainWindow", "Параметр 1"))
        item = self.tableWidget_3.item(2, 0)
        item.setText(_translate("MainWindow", "Параметр 2"))
        item = self.tableWidget_3.item(3, 0)
        item.setText(_translate("MainWindow", "Параметр 3"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.pushButton_27.setText(_translate("MainWindow", "Глобальные настройки"))
        self.label_9.setText(_translate("MainWindow", "Шрифт:"))
        self.pushButton_11.setText(_translate("MainWindow", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Таблица"))
        self.pushButton_5.setText(_translate("MainWindow", "Поиск"))
        self.pushButton_6.setText(_translate("MainWindow", "Таблица"))
        self.pushButton_9.setText(_translate("MainWindow", "Матрица парных сравнений"))
        self.pushButton_24.setText(_translate("MainWindow", "Сравнения у альтернатив"))
        self.pushButton_37.setText(_translate("MainWindow", "Итог"))
        self.pushButton_47.setText(_translate("MainWindow", "Нейросети"))
        self.pushButton_15.setText(_translate("MainWindow", "Очистить"))
        self.pushButton_16.setText(_translate("MainWindow", "Сохранить"))
        self.label_2.setText(_translate("MainWindow", "Размер таблицы:"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "6x6"))
        self.label_7.setText(_translate("MainWindow", "Вывод:"))
        self.label_10.setText(_translate("MainWindow", "Шрифт:"))
        self.pushButton_12.setText(_translate("MainWindow", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "МПС"))
        self.pushButton_20.setText(_translate("MainWindow", "Поиск"))
        self.pushButton_21.setText(_translate("MainWindow", "Таблица"))
        self.pushButton_22.setText(_translate("MainWindow", "Матрица парных сравнений"))
        self.pushButton_23.setText(_translate("MainWindow", "Сравнения у альтернатив"))
        self.pushButton_36.setText(_translate("MainWindow", "Итог"))
        self.pushButton_51.setText(_translate("MainWindow", "Нейросети"))
        self.label_4.setText(_translate("MainWindow", "Размер таблицы:"))
        self.pushButton_29.setText(_translate("MainWindow", "Сохранить"))
        self.label_5.setText(_translate("MainWindow", "6x6"))
        self.pushButton_30.setText(_translate("MainWindow", "Очистить"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_4.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_4.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("MainWindow", "Вывод:"))
        self.label_11.setText(_translate("MainWindow", "Шрифт:"))
        self.pushButton_13.setText(_translate("MainWindow", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Сравнение в Объектах"))
        self.pushButton_31.setText(_translate("MainWindow", "Поиск"))
        self.pushButton_32.setText(_translate("MainWindow", "Таблица"))
        self.pushButton_33.setText(_translate("MainWindow", "Матрица парных сравнений"))
        self.pushButton_34.setText(_translate("MainWindow", "Сравнения у альтернатив"))
        self.pushButton_35.setText(_translate("MainWindow", "Итог"))
        self.pushButton_50.setText(_translate("MainWindow", "Нейросети"))
        self.pushButton_43.setText(_translate("MainWindow", "Сохранить в excel"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Конечный результат"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Параметры"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Влияние параметров"))
        self.label_6.setText(_translate("MainWindow", "Итог:"))
        self.pushButton_44.setText(_translate("MainWindow", "Получить"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Альтернативы:"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Веса:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Завершение"))
        self.pushButton_17.setText(_translate("MainWindow", "Поиск"))
        self.pushButton_18.setText(_translate("MainWindow", "Таблица"))
        self.pushButton_19.setText(_translate("MainWindow", "Матрица парных сравнений"))
        self.pushButton_28.setText(_translate("MainWindow", "Сравнения у альтернатив"))
        self.pushButton_41.setText(_translate("MainWindow", "Итог"))
        self.pushButton_42.setText(_translate("MainWindow", "Нейросети"))
        self.label_12.setText(_translate("MainWindow", "Настройка нейросетей (Страница № 1)"))
        self.groupBox.setTitle(_translate("MainWindow", "Основная настройка"))
        self.label_14.setText(_translate("MainWindow", "Количество входных параметров:"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "10"))
        self.label_15.setText(_translate("MainWindow", "Количество выходных параметров:"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "10"))
        self.pushButton_46.setText(_translate("MainWindow", "Создать модель"))
        self.label_20.setText(_translate("MainWindow", "Выбор функции оптимизации:"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Adam"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "SGD"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "20"))
        self.label_17.setText(_translate("MainWindow", "Количество нейронов H:"))
        self.label_19.setText(_translate("MainWindow", "Выбор функции активации:"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Sigmoid"))
        self.label_18.setText(_translate("MainWindow", "Количество H слоёв:"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_10.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_10.setItemText(5, _translate("MainWindow", "5"))
        self.label_43.setText(_translate("MainWindow", "Наличие модели:"))
        self.label_44.setText(_translate("MainWindow", "Нет"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Дополнительная настройка"))
        self.label_21.setText(_translate("MainWindow", "Работа слоёв, используя:"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "CPU"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "CUDA"))
        self.label_22.setText(_translate("MainWindow", "Наличие CUDA:"))
        self.label_23.setText(_translate("MainWindow", "False"))
        self.label_24.setText(_translate("MainWindow", "Обучение, используя:"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "CPU"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "CUDA"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Информация о нейросети"))
        self.label_26.setText(_translate("MainWindow", "Количество H слоёв:"))
        self.label_27.setText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "Количество нейронов:"))
        self.label_29.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "Кол-во связей:"))
        self.label_31.setText(_translate("MainWindow", "0"))
        self.label_32.setText(_translate("MainWindow", "Средний loss:"))
        self.label_33.setText(_translate("MainWindow", "0.0"))
        self.label_34.setText(_translate("MainWindow", "Функция оптимизации:"))
        self.label_35.setText(_translate("MainWindow", "Adam"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Загрузка/Сохранение модели"))
        self.pushButton_48.setText(_translate("MainWindow", "Сохранить"))
        self.label_36.setText(_translate("MainWindow", "Путь:"))
        self.plainTextEdit_3.setPlaceholderText(_translate("MainWindow", "Здесь будет путь до вашей модели"))
        self.pushButton_54.setText(_translate("MainWindow", "Загрузить"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Загрузка базы для обучения"))
        self.pushButton_49.setText(_translate("MainWindow", "Выберите путь"))
        self.label_37.setText(_translate("MainWindow", "Путь:"))
        self.plainTextEdit_4.setPlaceholderText(_translate("MainWindow", "Здесь будет путь до вашей базы"))
        self.pushButton_57.setText(_translate("MainWindow", "<"))
        self.pushButton_58.setText(_translate("MainWindow", ">"))
        self.label_13.setText(_translate("MainWindow", "Работа с нейросетями (Страница № 2)"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Обучение"))
        self.label_38.setText(_translate("MainWindow", "Укажите количество эпох:"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "100"))
        self.label_39.setText(_translate("MainWindow", "Укажите коэфицент скорости обучения"))
        self.lineEdit_7.setText(_translate("MainWindow", "0.0001"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "0.001"))
        self.pushButton_53.setText(_translate("MainWindow", "Начать обучение:"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Использование"))
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Номер входа"))
        item = self.tableWidget_5.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Значение"))
        item = self.tableWidget_6.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Номер выхода"))
        item = self.tableWidget_6.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Значение"))
        self.label_41.setText(_translate("MainWindow", "Входные данные:"))
        self.label_42.setText(_translate("MainWindow", "Выходные данные:"))
        self.pushButton_55.setText(_translate("MainWindow", "Запустить нейросеть"))
        self.label_45.setText(_translate("MainWindow", "0"))
        self.HIDDENGRAPH.setTitle(_translate("MainWindow", "Обучение график"))
        self.pushButton_56.setText(_translate("MainWindow", "Отобразить график"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "LOSS"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "CUSTOM"))
        self.pushButton_59.setText(_translate("MainWindow", ">"))
        self.pushButton_60.setText(_translate("MainWindow", "<"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.NeuralNetworkTab), _translate("MainWindow", "Страница"))
from PyQt5 import QtWebEngineWidgets
